// ============================================================
// DentaCore ERP - Mock Data for Development (Dental Clinic)
// ============================================================

import {
  UserRole, Gender, AppointmentType, AppointmentStatus, Priority,
  InvoiceStatus, PaymentMethod, LeadStatus, LeadSource, TreatmentCategory,
  WorkflowStage, LabTestStatus, DocumentType, RoomType, RoomStatus,
  type Branch, type User, type Patient, type Appointment, type Treatment,
  type Invoice, type Payment, type Lead, type CallLog, type FollowUp,
  type Room, type ConsultationNote, type Prescription, type LabTest,
  type Package, type Triage, type Notification, type AuditLog,
  type AITranscription, type PatientDocument, type CommunicationLog,
  type SkinHistory, type MedicalHistory, type ActivityItem, type PatientPackage,
  type RoomAllocation,
} from "@/types";

// ---- Branches ----
export const mockBranches: Branch[] = [
  { id: "br-001", name: "DentaCore Main Dental", address: "123 Smile Plaza, Downtown", phone: "(555) 100-0001", email: "main@dentacore.com", isActive: true, createdAt: "2024-01-15" },
  { id: "br-002", name: "DentaCore Downtown", address: "456 City Center Ave", phone: "(555) 100-0002", email: "downtown@dentacore.com", isActive: true, createdAt: "2024-03-01" },
  { id: "br-003", name: "DentaCore Westside", address: "789 West Blvd, Suite 200", phone: "(555) 100-0003", email: "westside@dentacore.com", isActive: true, createdAt: "2024-06-15" },
  { id: "br-004", name: "DentaCore North", address: "321 North Park Dr", phone: "(555) 100-0004", email: "north@dentacore.com", isActive: true, createdAt: "2025-01-01" },
  { id: "br-005", name: "DentaCore South", address: "654 South Gate Mall", phone: "(555) 100-0005", email: "south@dentacore.com", isActive: false, createdAt: "2025-06-01" },
];

// ---- Users / Staff ----
export const mockUsers: User[] = [
  { id: "usr-001", email: "admin@dentacore.com", name: "Dr. Sarah Mitchell", phone: "(555) 201-0001", role: UserRole.ADMIN, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T08:30:00", createdAt: "2024-01-15" },
  { id: "usr-002", email: "dr.chen@dentacore.com", name: "Dr. Emily Chen", phone: "(555) 201-0002", role: UserRole.DOCTOR, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T07:45:00", createdAt: "2024-01-20" },
  { id: "usr-003", email: "dr.patel@dentacore.com", name: "Dr. Raj Patel", phone: "(555) 201-0003", role: UserRole.DOCTOR, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T08:00:00", createdAt: "2024-02-01" },
  { id: "usr-004", email: "dr.kim@dentacore.com", name: "Dr. Lisa Kim", phone: "(555) 201-0004", role: UserRole.DOCTOR, branchId: "br-002", branchName: "Downtown", isActive: true, lastLogin: "2026-04-04T17:30:00", createdAt: "2024-03-15" },
  { id: "usr-005", email: "reception@dentacore.com", name: "Maria Santos", phone: "(555) 201-0005", role: UserRole.RECEPTIONIST, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T07:55:00", createdAt: "2024-01-20" },
  { id: "usr-006", email: "billing@dentacore.com", name: "James Wilson", phone: "(555) 201-0006", role: UserRole.BILLING, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T08:10:00", createdAt: "2024-02-15" },
  { id: "usr-007", email: "callcenter@dentacore.com", name: "Sophie Taylor", phone: "(555) 201-0007", role: UserRole.CALL_CENTER, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T08:00:00", createdAt: "2024-04-01" },
  { id: "usr-008", email: "nurse@dentacore.com", name: "Rachel Green", phone: "(555) 201-0008", role: UserRole.ASSISTANT, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T07:50:00", createdAt: "2024-03-01" },
  { id: "usr-009", email: "dr.williams@dentacore.com", name: "Dr. Mark Williams", phone: "(555) 201-0009", role: UserRole.DOCTOR, branchId: "br-003", branchName: "Westside", isActive: true, lastLogin: "2026-04-04T16:00:00", createdAt: "2024-06-20" },
  { id: "usr-010", email: "superadmin@dentacore.com", name: "Alex Thompson", phone: "(555) 201-0010", role: UserRole.SUPER_ADMIN, branchId: "br-001", branchName: "Main Dental", isActive: true, lastLogin: "2026-04-05T09:00:00", createdAt: "2024-01-01" },
];

// ---- Patients ----
export const mockPatients: Patient[] = [
  { id: "pt-001", patientCode: "PT-0001", firstName: "Olivia", lastName: "Harper", email: "olivia.h@email.com", phone: "(555) 301-0001", dateOfBirth: "1992-05-14", age: 33, gender: Gender.FEMALE, address: "45 Oak Street", city: "Westville", emergencyContact: "David Harper", emergencyPhone: "(555) 301-0099", bloodType: "O+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Lidocaine", "Latex"], skinType: "TYPE_III", lastVisit: "2026-03-28", nextAppointment: "2026-04-05", outstandingBalance: 250, createdAt: "2025-01-10" },
  { id: "pt-002", patientCode: "PT-0002", firstName: "Ethan", lastName: "Brooks", email: "ethan.b@email.com", phone: "(555) 301-0002", dateOfBirth: "1988-11-22", age: 37, gender: Gender.MALE, address: "78 Pine Avenue", city: "Downtown", emergencyContact: "Sarah Brooks", emergencyPhone: "(555) 301-0098", bloodType: "A+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Penicillin"], skinType: "TYPE_II", lastVisit: "2026-04-01", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-02-05" },
  { id: "pt-003", patientCode: "PT-0003", firstName: "Sophia", lastName: "Martinez", email: "sophia.m@email.com", phone: "(555) 301-0003", dateOfBirth: "1995-08-30", age: 30, gender: Gender.FEMALE, address: "22 Maple Lane", city: "Northside", emergencyContact: "Carlos Martinez", emergencyPhone: "(555) 301-0097", bloodType: "B+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: [], skinType: "TYPE_IV", lastVisit: "2026-04-03", nextAppointment: "2026-04-07", outstandingBalance: 180, createdAt: "2025-01-20" },
  { id: "pt-004", patientCode: "PT-0004", firstName: "Liam", lastName: "Johnson", email: "liam.j@email.com", phone: "(555) 301-0004", dateOfBirth: "1985-03-17", age: 41, gender: Gender.MALE, address: "110 Cedar Rd", city: "Westville", emergencyContact: "Amy Johnson", emergencyPhone: "(555) 301-0096", bloodType: "AB+", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: ["Amoxicillin", "Latex"], skinType: "TYPE_II", lastVisit: "2026-03-25", nextAppointment: "2026-04-10", outstandingBalance: 500, createdAt: "2025-03-15" },
  { id: "pt-005", patientCode: "PT-0005", firstName: "Ava", lastName: "Williams", email: "ava.w@email.com", phone: "(555) 301-0005", dateOfBirth: "1999-12-05", age: 26, gender: Gender.FEMALE, address: "55 Birch Street", city: "Eastside", emergencyContact: "Tom Williams", emergencyPhone: "(555) 301-0095", bloodType: "O-", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: [], skinType: "TYPE_V", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-04-01" },
  { id: "pt-006", patientCode: "PT-0006", firstName: "Noah", lastName: "Davis", email: "noah.d@email.com", phone: "(555) 301-0006", dateOfBirth: "1990-07-21", age: 35, gender: Gender.MALE, address: "300 Elm Dr", city: "Downtown", emergencyContact: "Karen Davis", emergencyPhone: "(555) 301-0094", bloodType: "A-", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Ibuprofen"], skinType: "TYPE_I", lastVisit: "2026-03-30", outstandingBalance: 75, createdAt: "2025-02-20" },
  { id: "pt-007", patientCode: "PT-0007", firstName: "Isabella", lastName: "Garcia", email: "isabella.g@email.com", phone: "(555) 301-0007", dateOfBirth: "1993-01-10", age: 33, gender: Gender.FEMALE, address: "88 Walnut Ave", city: "Southside", emergencyContact: "Miguel Garcia", emergencyPhone: "(555) 301-0093", bloodType: "B-", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: ["Nickel"], skinType: "TYPE_IV", lastVisit: "2026-04-02", nextAppointment: "2026-04-06", outstandingBalance: 0, createdAt: "2025-05-10" },
  { id: "pt-008", patientCode: "PT-0008", firstName: "Mason", lastName: "Brown", email: "mason.b@email.com", phone: "(555) 301-0008", dateOfBirth: "1987-09-03", age: 38, gender: Gender.MALE, address: "42 Spruce Ct", city: "Westville", emergencyContact: "Linda Brown", emergencyPhone: "(555) 301-0092", bloodType: "O+", branchId: "br-003", branchName: "Westside", assignedDoctorId: "usr-009", assignedDoctorName: "Dr. Mark Williams", isActive: true, allergies: [], skinType: "TYPE_III", lastVisit: "2026-03-20", outstandingBalance: 320, createdAt: "2025-01-05" },
  { id: "pt-009", patientCode: "PT-0009", firstName: "Emma", lastName: "Wilson", email: "emma.w@email.com", phone: "(555) 301-0009", dateOfBirth: "1997-04-28", age: 28, gender: Gender.FEMALE, address: "15 Ash Blvd", city: "Northside", emergencyContact: "Paul Wilson", emergencyPhone: "(555) 301-0091", bloodType: "A+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Nickel"], skinType: "TYPE_II", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-06-15" },
  { id: "pt-010", patientCode: "PT-0010", firstName: "Charlotte", lastName: "Lee", email: "charlotte.l@email.com", phone: "(555) 301-0010", dateOfBirth: "1991-06-12", age: 34, gender: Gender.FEMALE, address: "200 Cherry Lane", city: "Eastside", emergencyContact: "Robert Lee", emergencyPhone: "(555) 301-0090", bloodType: "AB-", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Aspirin"], skinType: "TYPE_VI", lastVisit: "2026-04-01", nextAppointment: "2026-04-08", outstandingBalance: 150, createdAt: "2025-03-01" },
  { id: "pt-011", patientCode: "PT-0011", firstName: "James", lastName: "Anderson", email: "james.a@email.com", phone: "(555) 301-0011", dateOfBirth: "1983-02-14", age: 43, gender: Gender.MALE, address: "67 Poplar Way", city: "Downtown", emergencyContact: "Monica Anderson", emergencyPhone: "(555) 301-0089", bloodType: "O+", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: [], skinType: "TYPE_I", lastVisit: "2026-03-15", outstandingBalance: 0, createdAt: "2025-07-01" },
  { id: "pt-012", patientCode: "PT-0012", firstName: "Mia", lastName: "Thomas", email: "mia.t@email.com", phone: "(555) 301-0012", dateOfBirth: "1996-10-08", age: 29, gender: Gender.FEMALE, address: "33 Willow St", city: "Southside", emergencyContact: "Chris Thomas", emergencyPhone: "(555) 301-0088", bloodType: "B+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: false, allergies: ["Codeine"], skinType: "TYPE_III", lastVisit: "2026-01-10", outstandingBalance: 0, createdAt: "2025-08-20" },
  { id: "pt-013", patientCode: "PT-0013", firstName: "Benjamin", lastName: "Taylor", email: "ben.t@email.com", phone: "(555) 301-0013", dateOfBirth: "1994-08-19", age: 31, gender: Gender.MALE, address: "99 Magnolia Blvd", city: "Westville", emergencyContact: "Jennifer Taylor", emergencyPhone: "(555) 301-0087", bloodType: "A+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: [], skinType: "TYPE_III", lastVisit: "2026-04-03", nextAppointment: "2026-04-12", outstandingBalance: 0, createdAt: "2025-04-15" },
  { id: "pt-014", patientCode: "PT-0014", firstName: "Amelia", lastName: "Moore", email: "amelia.m@email.com", phone: "(555) 301-0014", dateOfBirth: "1989-12-25", age: 36, gender: Gender.FEMALE, address: "171 Ivy Circle", city: "Northside", emergencyContact: "Greg Moore", emergencyPhone: "(555) 301-0086", bloodType: "O+", branchId: "br-003", branchName: "Westside", assignedDoctorId: "usr-009", assignedDoctorName: "Dr. Mark Williams", isActive: true, allergies: ["NSAIDs"], skinType: "TYPE_II", lastVisit: "2026-03-29", nextAppointment: "2026-04-05", outstandingBalance: 420, createdAt: "2025-05-01" },
  { id: "pt-015", patientCode: "PT-0015", firstName: "Lucas", lastName: "Jackson", email: "lucas.j@email.com", phone: "(555) 301-0015", dateOfBirth: "2000-03-07", age: 26, gender: Gender.MALE, address: "58 Hazel Rd", city: "Eastside", emergencyContact: "Diana Jackson", emergencyPhone: "(555) 301-0085", bloodType: "AB+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: [], skinType: "TYPE_IV", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-09-01" },
  { id: "pt-016", patientCode: "PT-0016", firstName: "Harper", lastName: "White", email: "harper.w@email.com", phone: "(555) 301-0016", dateOfBirth: "1998-06-30", age: 27, gender: Gender.FEMALE, address: "82 Dogwood Ln", city: "Downtown", emergencyContact: "Mark White", emergencyPhone: "(555) 301-0084", bloodType: "B-", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Sulfa"], skinType: "TYPE_I", lastVisit: "2026-04-02", outstandingBalance: 0, createdAt: "2025-10-15" },
  { id: "pt-017", patientCode: "PT-0017", firstName: "Alexander", lastName: "Harris", email: "alex.h@email.com", phone: "(555) 301-0017", dateOfBirth: "1986-11-11", age: 39, gender: Gender.MALE, address: "444 Cypress Ave", city: "Southside", emergencyContact: "Nancy Harris", emergencyPhone: "(555) 301-0083", bloodType: "A-", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: [], skinType: "TYPE_III", lastVisit: "2026-03-18", outstandingBalance: 200, createdAt: "2025-06-20" },
  { id: "pt-018", patientCode: "PT-0018", firstName: "Ella", lastName: "Clark", email: "ella.c@email.com", phone: "(555) 301-0018", dateOfBirth: "2001-02-15", age: 25, gender: Gender.FEMALE, address: "19 Redwood St", city: "Westville", emergencyContact: "Steven Clark", emergencyPhone: "(555) 301-0082", bloodType: "O+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Articaine"], skinType: "TYPE_V", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-11-01" },
  { id: "pt-019", patientCode: "PT-0019", firstName: "Daniel", lastName: "Lewis", email: "daniel.l@email.com", phone: "(555) 301-0019", dateOfBirth: "1992-09-22", age: 33, gender: Gender.MALE, address: "263 Juniper Dr", city: "Northside", emergencyContact: "Laura Lewis", emergencyPhone: "(555) 301-0081", bloodType: "A+", branchId: "br-003", branchName: "Westside", assignedDoctorId: "usr-009", assignedDoctorName: "Dr. Mark Williams", isActive: true, allergies: [], skinType: "TYPE_II", lastVisit: "2026-03-22", outstandingBalance: 0, createdAt: "2025-07-10" },
  { id: "pt-020", patientCode: "PT-0020", firstName: "Grace", lastName: "Robinson", email: "grace.r@email.com", phone: "(555) 301-0020", dateOfBirth: "1995-04-03", age: 30, gender: Gender.FEMALE, address: "77 Sequoia Blvd", city: "Downtown", emergencyContact: "Kevin Robinson", emergencyPhone: "(555) 301-0080", bloodType: "B+", branchId: "br-001", branchName: "Main Dental", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Eugenol"], skinType: "TYPE_III", lastVisit: "2026-04-03", nextAppointment: "2026-04-09", outstandingBalance: 95, createdAt: "2025-12-01" },
];

// ---- Appointments (Today + This Week) ----
// Dates are relative to "now" so the dashboard always has today's data.
function isoDay(offsetDays = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}
const today = isoDay(0);
export const mockAppointments: Appointment[] = [
  { id: "apt-001", appointmentCode: "APT-0001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", roomId: "rm-001", roomName: "Room 1", date: today, startTime: "09:00", endTime: "09:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.COMPLETED, priority: Priority.NORMAL, workflowStage: WorkflowStage.HISTORY_UPDATE, createdBy: "usr-005", createdAt: "2026-03-28", notes: "Follow-up on RCT #36 (lower left molar)" },
  { id: "apt-002", appointmentCode: "APT-0002", patientId: "pt-002", patientName: "Ethan Brooks", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Dental", roomId: "rm-002", roomName: "Room 2", date: today, startTime: "09:00", endTime: "09:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.IN_PROGRESS, priority: Priority.NORMAL, workflowStage: WorkflowStage.TREATMENT, createdBy: "usr-005", createdAt: "2026-03-30", notes: "Crown prep #26 — session 1 of 2" },
  { id: "apt-003", appointmentCode: "APT-0003", patientId: "pt-005", patientName: "Ava Williams", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "10:00", endTime: "10:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.WAITING, priority: Priority.NORMAL, workflowStage: WorkflowStage.WAITING, createdBy: "usr-005", createdAt: "2026-04-01", notes: "New consultation — tooth sensitivity upper right" },
  { id: "apt-004", appointmentCode: "APT-0004", patientId: "pt-009", patientName: "Emma Wilson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "10:00", endTime: "10:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.CHECKED_IN, priority: Priority.NORMAL, workflowStage: WorkflowStage.CHECKIN, checkinTime: "09:52", createdBy: "usr-005", createdAt: "2026-04-02", notes: "Bleeding gums assessment — periodontal check" },
  { id: "apt-005", appointmentCode: "APT-0005", patientId: "pt-015", patientName: "Lucas Jackson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "10:30", endTime: "11:15", type: AppointmentType.PROCEDURE, status: AppointmentStatus.CONFIRMED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-007", createdAt: "2026-04-03", notes: "Composite filling #15 (upper left second molar)" },
  { id: "apt-006", appointmentCode: "APT-0006", patientId: "pt-018", patientName: "Ella Clark", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "11:00", endTime: "11:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.CONFIRMED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-03" },
  { id: "apt-007", appointmentCode: "APT-0007", patientId: "pt-014", patientName: "Amelia Moore", doctorId: "usr-009", doctorName: "Dr. Mark Williams", branchId: "br-003", branchName: "Westside", date: today, startTime: "09:30", endTime: "10:15", type: AppointmentType.PROCEDURE, status: AppointmentStatus.IN_PROGRESS, priority: Priority.NORMAL, workflowStage: WorkflowStage.TREATMENT, createdBy: "usr-005", createdAt: "2026-03-29", notes: "Scaling & polishing (full mouth)" },
  { id: "apt-008", appointmentCode: "APT-0008", patientId: "pt-003", patientName: "Sophia Martinez", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "11:30", endTime: "12:00", type: AppointmentType.REVIEW, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-01" },
  { id: "apt-009", appointmentCode: "APT-0009", patientId: "pt-006", patientName: "Noah Davis", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "11:00", endTime: "11:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.SCHEDULED, priority: Priority.URGENT, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-04", notes: "Extraction #38 (impacted wisdom tooth)" },
  { id: "apt-010", appointmentCode: "APT-0010", patientId: "pt-010", patientName: "Charlotte Lee", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "14:00", endTime: "14:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-007", createdAt: "2026-04-04" },
  { id: "apt-011", appointmentCode: "APT-0011", patientId: "pt-013", patientName: "Benjamin Taylor", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "14:00", endTime: "14:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-02", notes: "Ortho adjustment — clear aligner review" },
  { id: "apt-012", appointmentCode: "APT-0012", patientId: "pt-016", patientName: "Harper White", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "15:00", endTime: "15:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-03" },
  { id: "apt-013", appointmentCode: "APT-0013", patientId: "pt-020", patientName: "Grace Robinson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: today, startTime: "15:00", endTime: "15:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-007", createdAt: "2026-04-04" },
  { id: "apt-014", appointmentCode: "APT-0014", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Dental", date: isoDay(2), startTime: "09:00", endTime: "09:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-05" },
  { id: "apt-015", appointmentCode: "APT-0015", patientId: "pt-004", patientName: "Liam Johnson", doctorId: "usr-004", doctorName: "Dr. Lisa Kim", branchId: "br-002", branchName: "Downtown", date: isoDay(5), startTime: "10:00", endTime: "10:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-01", notes: "Veneer fitting — upper anteriors (11, 21)" },
  // Cancelled / No-show
  { id: "apt-016", appointmentCode: "APT-0016", patientId: "pt-011", patientName: "James Anderson", doctorId: "usr-004", doctorName: "Dr. Lisa Kim", branchId: "br-002", branchName: "Downtown", date: today, startTime: "09:00", endTime: "09:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.NO_SHOW, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-03-28" },
  { id: "apt-017", appointmentCode: "APT-0017", patientId: "pt-008", patientName: "Mason Brown", doctorId: "usr-009", doctorName: "Dr. Mark Williams", branchId: "br-003", branchName: "Westside", date: today, startTime: "11:00", endTime: "11:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.CANCELLED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-03-25", notes: "Patient requested cancellation" },
];

// ---- Treatments Catalog ----
export const mockTreatments: Treatment[] = [
  { id: "trt-001", name: "Scaling & Polishing", category: TreatmentCategory.PREVENTIVE, description: "Full-mouth scaling, polishing, and oral hygiene review", duration: 45, basePrice: 60, isActive: true },
  { id: "trt-002", name: "Oral Examination", category: TreatmentCategory.DIAGNOSTIC, description: "Comprehensive oral exam with charting and treatment planning", duration: 20, basePrice: 30, isActive: true },
  { id: "trt-003", name: "Composite Filling (1 surface)", category: TreatmentCategory.RESTORATIVE, description: "Tooth-colored composite resin filling — single surface", duration: 30, basePrice: 80, isActive: true },
  { id: "trt-004", name: "Composite Filling (2+ surface)", category: TreatmentCategory.RESTORATIVE, description: "Tooth-colored composite resin filling — multi-surface", duration: 45, basePrice: 130, isActive: true },
  { id: "trt-005", name: "Root Canal Treatment — Molar", category: TreatmentCategory.ENDODONTIC, description: "Endodontic therapy for molar teeth (3–4 canals)", duration: 90, basePrice: 450, isActive: true },
  { id: "trt-006", name: "Root Canal Treatment — Anterior", category: TreatmentCategory.ENDODONTIC, description: "Endodontic therapy for front teeth (single canal)", duration: 60, basePrice: 250, isActive: true },
  { id: "trt-007", name: "Porcelain Crown (PFM)", category: TreatmentCategory.PROSTHODONTIC, description: "Porcelain-fused-to-metal crown restoration", duration: 60, basePrice: 450, isActive: true },
  { id: "trt-008", name: "Zirconia Crown", category: TreatmentCategory.PROSTHODONTIC, description: "Full-contour zirconia crown (metal-free)", duration: 60, basePrice: 650, isActive: true },
  { id: "trt-009", name: "In-office Teeth Whitening", category: TreatmentCategory.COSMETIC, description: "Chairside professional whitening (single session)", duration: 60, basePrice: 300, isActive: true },
  { id: "trt-010", name: "Tooth Extraction (Simple)", category: TreatmentCategory.SURGICAL, description: "Uncomplicated extraction of erupted tooth", duration: 30, basePrice: 80, isActive: true },
  { id: "trt-011", name: "Wisdom Tooth Removal", category: TreatmentCategory.SURGICAL, description: "Surgical removal of impacted third molar", duration: 75, basePrice: 350, isActive: true },
  { id: "trt-012", name: "Dental Implant", category: TreatmentCategory.SURGICAL, description: "Titanium implant placement (surgical phase)", duration: 90, basePrice: 1800, isActive: true },
];

// ---- Invoices ----
export const mockInvoices: Invoice[] = [
  { id: "inv-001", invoiceNumber: "INV-2026-0001", patientId: "pt-001", patientName: "Olivia Harper", branchId: "br-001", items: [{ description: "Follow-up Consultation", type: "CONSULTATION", quantity: 1, unitPrice: 100, total: 100 }, { description: "Fluoride Varnish", type: "PRODUCT", quantity: 1, unitPrice: 45, total: 45 }], subtotal: 145, discount: 0, discountType: "FIXED", tax: 10.15, total: 155.15, status: InvoiceStatus.PAID, dueDate: "2026-03-28", payments: [], createdById: "usr-006", createdAt: "2026-03-28" },
  { id: "inv-002", invoiceNumber: "INV-2026-0002", patientId: "pt-002", patientName: "Ethan Brooks", branchId: "br-001", appointmentId: "apt-002", items: [{ description: "Root Canal Treatment — Molar - Session 3", type: "PROCEDURE", quantity: 1, unitPrice: 450, total: 450 }], subtotal: 450, discount: 0, discountType: "FIXED", tax: 31.50, total: 481.50, status: InvoiceStatus.PENDING, dueDate: "2026-04-05", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
  { id: "inv-003", invoiceNumber: "INV-2026-0003", patientId: "pt-003", patientName: "Sophia Martinez", branchId: "br-001", items: [{ description: "Scaling & Polishing", type: "PROCEDURE", quantity: 1, unitPrice: 200, total: 200 }, { description: "Consultation Fee", type: "CONSULTATION", quantity: 1, unitPrice: 100, total: 100 }], subtotal: 300, discount: 20, discountType: "PERCENTAGE", tax: 16.80, total: 256.80, status: InvoiceStatus.PARTIAL, dueDate: "2026-04-10", payments: [], createdById: "usr-006", createdAt: "2026-04-03" },
  { id: "inv-004", invoiceNumber: "INV-2026-0004", patientId: "pt-004", patientName: "Liam Johnson", branchId: "br-002", items: [{ description: "Porcelain Crown (PFM) #36", type: "PROCEDURE", quantity: 1, unitPrice: 350, total: 350 }, { description: "Bridge - 3 unit (anterior)", type: "PROCEDURE", quantity: 1, unitPrice: 500, total: 500 }], subtotal: 850, discount: 50, discountType: "FIXED", tax: 56, total: 856, status: InvoiceStatus.OVERDUE, dueDate: "2026-03-25", payments: [], createdById: "usr-006", createdAt: "2026-03-20" },
  { id: "inv-005", invoiceNumber: "INV-2026-0005", patientId: "pt-005", patientName: "Ava Williams", branchId: "br-001", items: [{ description: "Consultation - Tooth Sensitivity", type: "CONSULTATION", quantity: 1, unitPrice: 100, total: 100 }], subtotal: 100, discount: 0, discountType: "FIXED", tax: 7, total: 107, status: InvoiceStatus.PENDING, dueDate: "2026-04-12", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
  { id: "inv-006", invoiceNumber: "INV-2026-0006", patientId: "pt-006", patientName: "Noah Davis", branchId: "br-001", items: [{ description: "Full-mouth X-ray Series", type: "PROCEDURE", quantity: 1, unitPrice: 300, total: 300 }], subtotal: 300, discount: 0, discountType: "FIXED", tax: 21, total: 321, status: InvoiceStatus.PAID, dueDate: "2026-03-30", payments: [], createdById: "usr-006", createdAt: "2026-03-30" },
  { id: "inv-007", invoiceNumber: "INV-2026-0007", patientId: "pt-007", patientName: "Isabella Garcia", branchId: "br-002", items: [{ description: "Composite Filling (1 surface)", type: "PROCEDURE", quantity: 1, unitPrice: 150, total: 150 }, { description: "Fluoride Application", type: "PROCEDURE", quantity: 1, unitPrice: 75, total: 75 }], subtotal: 225, discount: 0, discountType: "FIXED", tax: 15.75, total: 240.75, status: InvoiceStatus.PAID, dueDate: "2026-04-02", payments: [], createdById: "usr-006", createdAt: "2026-04-02" },
  { id: "inv-008", invoiceNumber: "INV-2026-0008", patientId: "pt-008", patientName: "Mason Brown", branchId: "br-003", items: [{ description: "Dental Implant - Surgical Phase", type: "PROCEDURE", quantity: 1, unitPrice: 400, total: 400 }], subtotal: 400, discount: 0, discountType: "FIXED", tax: 28, total: 428, status: InvoiceStatus.OVERDUE, dueDate: "2026-03-27", payments: [], createdById: "usr-006", createdAt: "2026-03-20" },
  { id: "inv-009", invoiceNumber: "INV-2026-0009", patientId: "pt-009", patientName: "Emma Wilson", branchId: "br-001", items: [{ description: "Consultation - Bleeding Gums", type: "CONSULTATION", quantity: 1, unitPrice: 100, total: 100 }, { description: "Chlorhexidine Mouthwash", type: "PRODUCT", quantity: 1, unitPrice: 35, total: 35 }], subtotal: 135, discount: 0, discountType: "FIXED", tax: 9.45, total: 144.45, status: InvoiceStatus.PAID, dueDate: "2026-04-04", payments: [], createdById: "usr-006", createdAt: "2026-04-04" },
  { id: "inv-010", invoiceNumber: "INV-2026-0010", patientId: "pt-010", patientName: "Charlotte Lee", branchId: "br-001", items: [{ description: "Glow Package - Session 4 of 6", type: "PACKAGE", quantity: 1, unitPrice: 0, total: 0 }], subtotal: 0, discount: 0, discountType: "FIXED", tax: 0, total: 0, status: InvoiceStatus.PAID, dueDate: "2026-04-01", payments: [], createdById: "usr-006", createdAt: "2026-04-01", notes: "Package deduction" },
  { id: "inv-011", invoiceNumber: "INV-2026-0011", patientId: "pt-014", patientName: "Amelia Moore", branchId: "br-003", items: [{ description: "Root Canal - Anterior", type: "PROCEDURE", quantity: 1, unitPrice: 250, total: 250 }, { description: "Post-op care kit", type: "PRODUCT", quantity: 1, unitPrice: 65, total: 65 }], subtotal: 315, discount: 15, discountType: "PERCENTAGE", tax: 18.74, total: 286.49, status: InvoiceStatus.PENDING, dueDate: "2026-04-12", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
  { id: "inv-012", invoiceNumber: "INV-2026-0012", patientId: "pt-017", patientName: "Alexander Harris", branchId: "br-002", items: [{ description: "Fluoride Application (3 sites)", type: "PROCEDURE", quantity: 3, unitPrice: 100, total: 300 }], subtotal: 300, discount: 50, discountType: "FIXED", tax: 17.50, total: 267.50, status: InvoiceStatus.DRAFT, dueDate: "2026-04-15", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
];

// ---- Leads ----
export const mockLeads: Lead[] = [
  { id: "ld-001", name: "Rebecca Stone", phone: "(555) 401-0001", email: "rebecca.s@email.com", source: LeadSource.CALL, status: LeadStatus.NEW, interest: "Teeth Whitening", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Called asking about teeth whitening options", createdAt: "2026-04-05T09:15:00", updatedAt: "2026-04-05T09:15:00" },
  { id: "ld-002", name: "Michael Foster", phone: "(555) 401-0002", source: LeadSource.WEBSITE, status: LeadStatus.CONTACTED, interest: "Cosmetic Dentistry", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Filled form on website, interested in veneers", callbackDate: "2026-04-06T10:00:00", createdAt: "2026-04-04T14:30:00", updatedAt: "2026-04-05T08:00:00" },
  { id: "ld-003", name: "Jessica Wright", phone: "(555) 401-0003", email: "jess.w@email.com", source: LeadSource.SOCIAL_MEDIA, status: LeadStatus.INTERESTED, interest: "Dental Implant", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Saw Instagram post about dental implants, very interested", callbackDate: "2026-04-05T14:00:00", createdAt: "2026-04-03T11:00:00", updatedAt: "2026-04-04T16:00:00" },
  { id: "ld-004", name: "Andrew Kim", phone: "(555) 401-0004", source: LeadSource.REFERRAL, status: LeadStatus.BOOKED, interest: "Clear Aligners", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Referred by pt-002 (Ethan Brooks), booked aligner consultation", createdAt: "2026-04-02T09:00:00", updatedAt: "2026-04-04T10:00:00" },
  { id: "ld-005", name: "Diana Murphy", phone: "(555) 401-0005", source: LeadSource.WALK_IN, status: LeadStatus.NOT_INTERESTED, interest: "Root Canal", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-002", notes: "Walked in to ask about pricing, said too expensive", createdAt: "2026-04-01T15:30:00", updatedAt: "2026-04-01T16:00:00" },
  { id: "ld-006", name: "Thomas Reed", phone: "(555) 401-0006", email: "tom.r@email.com", source: LeadSource.CALL, status: LeadStatus.FOLLOW_UP, interest: "Crown / Bridge", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Wants more info about crown / bridge options", callbackDate: "2026-04-07T11:00:00", createdAt: "2026-04-03T13:00:00", updatedAt: "2026-04-05T09:00:00" },
  { id: "ld-007", name: "Sandra Mitchell", phone: "(555) 401-0007", source: LeadSource.WEBSITE, status: LeadStatus.NEW, interest: "Routine Checkup", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-003", createdAt: "2026-04-05T08:30:00", updatedAt: "2026-04-05T08:30:00" },
  { id: "ld-008", name: "Kevin Park", phone: "(555) 401-0008", source: LeadSource.SOCIAL_MEDIA, status: LeadStatus.CONTACTED, interest: "Scaling & Polishing", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "TikTok inquiry about cleaning packages", callbackDate: "2026-04-05T16:00:00", createdAt: "2026-04-04T10:00:00", updatedAt: "2026-04-04T15:00:00" },
];

// ---- Packages ----
export const mockPackages: Package[] = [
  { id: "pkg-001", name: "Smile Essentials", description: "4 scaling & polishing sessions + 2 fluoride applications for year-round preventive care", treatments: [{ treatmentId: "trt-001", treatmentName: "Scaling & Polishing", sessions: 4 }, { treatmentId: "trt-002", treatmentName: "Oral Examination", sessions: 2 }], price: 300, validityDays: 365, isActive: true, subscriberCount: 12, createdAt: "2025-06-01" },
  { id: "pkg-002", name: "Perio Care Plan", description: "Quarterly deep cleaning & perio maintenance for patients with gum disease", treatments: [{ treatmentId: "trt-001", treatmentName: "Scaling & Polishing", sessions: 4 }], price: 500, validityDays: 365, isActive: true, subscriberCount: 8, createdAt: "2025-07-15" },
  { id: "pkg-003", name: "Full Mouth Rehab", description: "Comprehensive rehab: crowns, root canal, and implants for extensive restoration", treatments: [{ treatmentId: "trt-007", treatmentName: "Porcelain Crown (PFM)", sessions: 4 }, { treatmentId: "trt-005", treatmentName: "Root Canal Treatment — Molar", sessions: 2 }, { treatmentId: "trt-012", treatmentName: "Dental Implant", sessions: 1 }], price: 5500, validityDays: 365, isActive: true, subscriberCount: 5, createdAt: "2025-09-01" },
  { id: "pkg-004", name: "Cosmetic Smile Makeover", description: "In-office whitening + 4 porcelain veneers (upper anteriors)", treatments: [{ treatmentId: "trt-009", treatmentName: "In-office Teeth Whitening", sessions: 1 }, { treatmentId: "trt-007", treatmentName: "Porcelain Crown (PFM)", sessions: 4 }], price: 2800, validityDays: 180, isActive: true, subscriberCount: 3, createdAt: "2025-10-01" },
  { id: "pkg-005", name: "Family Annual Plan", description: "2 cleanings + 2 exams per year for each family member — ideal for preventive care", treatments: [{ treatmentId: "trt-001", treatmentName: "Scaling & Polishing", sessions: 2 }, { treatmentId: "trt-002", treatmentName: "Oral Examination", sessions: 2 }], price: 200, validityDays: 365, isActive: true, subscriberCount: 15, createdAt: "2025-11-01" },
];

// ---- Rooms ----
export const mockRooms: Room[] = [
  { id: "rm-001", branchId: "br-001", name: "Operatory 1 - Exam", type: RoomType.CONSULTATION, status: RoomStatus.OCCUPIED, isAvailable: false, capacity: 2, currentPatientName: "Olivia Harper", currentDoctorName: "Dr. Emily Chen", occupiedSince: "2026-04-05T09:00:00" },
  { id: "rm-002", branchId: "br-001", name: "Operatory 2 - Surgery", type: RoomType.PROCEDURE, status: RoomStatus.OCCUPIED, isAvailable: false, capacity: 3, currentPatientName: "Ethan Brooks", currentDoctorName: "Dr. Raj Patel", occupiedSince: "2026-04-05T09:00:00" },
  { id: "rm-003", branchId: "br-001", name: "Operatory 3 - Restorative", type: RoomType.PROCEDURE, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 2 },
  { id: "rm-004", branchId: "br-001", name: "Operatory 4 - Exam", type: RoomType.CONSULTATION, status: RoomStatus.CLEANING, isAvailable: false, capacity: 2 },
  { id: "rm-005", branchId: "br-001", name: "Recovery Bay", type: RoomType.RECOVERY, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 4 },
  { id: "rm-006", branchId: "br-001", name: "Waiting Area", type: RoomType.WAITING, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 15 },
  { id: "rm-007", branchId: "br-002", name: "Operatory 1 - Exam", type: RoomType.CONSULTATION, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 2 },
  { id: "rm-008", branchId: "br-002", name: "Operatory 2 - Restorative", type: RoomType.PROCEDURE, status: RoomStatus.MAINTENANCE, isAvailable: false, capacity: 3 },
  { id: "rm-009", branchId: "br-003", name: "Operatory 1 - Multi-Purpose", type: RoomType.PROCEDURE, status: RoomStatus.OCCUPIED, isAvailable: false, capacity: 3, currentPatientName: "Amelia Moore", currentDoctorName: "Dr. Mark Williams", occupiedSince: "2026-04-05T09:30:00" },
  { id: "rm-010", branchId: "br-003", name: "Operatory 2 - Exam", type: RoomType.CONSULTATION, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 2 },
];

// ---- Follow-Ups ----
export const mockFollowUps: FollowUp[] = [
  { id: "fu-001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-04-07", reason: "Post-RCT review after 2 weeks", status: "PENDING", createdAt: "2026-03-28" },
  { id: "fu-002", patientId: "pt-002", patientName: "Ethan Brooks", doctorId: "usr-003", doctorName: "Dr. Raj Patel", dueDate: "2026-04-19", reason: "Crown cementation review - assess fit after trial", status: "PENDING", createdAt: "2026-04-05" },
  { id: "fu-003", patientId: "pt-006", patientName: "Noah Davis", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-04-05", reason: "Review oral hygiene adherence post-extraction", status: "PENDING", createdAt: "2026-03-30" },
  { id: "fu-004", patientId: "pt-008", patientName: "Mason Brown", doctorId: "usr-009", doctorName: "Dr. Mark Williams", dueDate: "2026-04-03", reason: "Implant osseointegration check", status: "MISSED", createdAt: "2026-03-20" },
  { id: "fu-005", patientId: "pt-010", patientName: "Charlotte Lee", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-04-08", reason: "Package progress - cleaning plan review", status: "PENDING", createdAt: "2026-04-01" },
  { id: "fu-006", patientId: "pt-003", patientName: "Sophia Martinez", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-03-25", reason: "Post-extraction recovery check", status: "COMPLETED", completedAt: "2026-03-25", createdAt: "2026-03-15" },
  { id: "fu-007", patientId: "pt-009", patientName: "Emma Wilson", doctorId: "usr-003", doctorName: "Dr. Raj Patel", dueDate: "2026-04-11", reason: "Perio treatment effectiveness review", status: "PENDING", createdAt: "2026-04-04" },
  { id: "fu-008", patientId: "pt-014", patientName: "Amelia Moore", doctorId: "usr-009", doctorName: "Dr. Mark Williams", dueDate: "2026-04-12", reason: "Wisdom tooth socket healing assessment", status: "PENDING", createdAt: "2026-04-05" },
];

// ---- Notifications ----
export const mockNotifications: Notification[] = [
  { id: "notif-001", userId: "usr-001", title: "New Patient Registration", message: "Ella Clark (PT-0018) has been registered", type: "SYSTEM", isRead: false, link: "/patients/pt-018", createdAt: "2026-04-05T08:45:00" },
  { id: "notif-002", userId: "usr-001", title: "Appointment No-Show", message: "James Anderson missed his 9:00 AM appointment", type: "APPOINTMENT", isRead: false, link: "/appointments", createdAt: "2026-04-05T09:15:00" },
  { id: "notif-003", userId: "usr-001", title: "Overdue Invoice", message: "Invoice INV-2026-0004 for Liam Johnson is overdue (Rs 856)", type: "BILLING", isRead: false, link: "/billing/inv-004", createdAt: "2026-04-05T08:00:00" },
  { id: "notif-004", userId: "usr-001", title: "Lab Results Ready", message: "Bitewing X-ray results ready for Olivia Harper", type: "LAB", isRead: true, link: "/patients/pt-001", createdAt: "2026-04-04T16:30:00" },
  { id: "notif-005", userId: "usr-002", title: "Upcoming Appointment", message: "Emma Wilson - Perio consultation at 10:00 AM", type: "APPOINTMENT", isRead: false, link: "/appointments/apt-004", createdAt: "2026-04-05T07:30:00" },
  { id: "notif-006", userId: "usr-001", title: "Follow-Up Due", message: "3 follow-ups are due today", type: "FOLLOW_UP", isRead: false, link: "/follow-ups", createdAt: "2026-04-05T08:00:00" },
  { id: "notif-007", userId: "usr-001", title: "Low Stock Alert", message: "Composite Resin A2 running low (5 units left)", type: "ALERT", isRead: true, createdAt: "2026-04-04T14:00:00" },
];

// ---- Call Logs ----
export const mockCallLogs: CallLog[] = [
  { id: "cl-001", leadId: "ld-001", callerName: "Rebecca Stone", userId: "usr-007", agentName: "Sophie Taylor", type: "INBOUND", duration: 180, notes: "Interested in teeth whitening, asked about pricing", outcome: "CALLBACK", createdAt: "2026-04-05T09:15:00" },
  { id: "cl-002", leadId: "ld-002", callerName: "Michael Foster", userId: "usr-007", agentName: "Sophie Taylor", type: "OUTBOUND", duration: 300, notes: "Called back about veneer inquiry, explained procedure", outcome: "CALLBACK", createdAt: "2026-04-05T08:30:00" },
  { id: "cl-003", leadId: "ld-003", callerName: "Jessica Wright", userId: "usr-007", agentName: "Sophie Taylor", type: "OUTBOUND", duration: 420, notes: "Discussed dental implant options and pricing", outcome: "BOOKED", createdAt: "2026-04-04T16:00:00" },
  { id: "cl-004", patientId: "pt-001", callerName: "Olivia Harper", userId: "usr-007", agentName: "Sophie Taylor", type: "INBOUND", duration: 120, notes: "Confirmed follow-up appointment", outcome: "INFO_PROVIDED", createdAt: "2026-04-04T11:00:00" },
  { id: "cl-005", leadId: "ld-005", callerName: "Diana Murphy", userId: "usr-007", agentName: "Sophie Taylor", type: "INBOUND", duration: 60, notes: "Asked about root canal pricing", outcome: "NOT_INTERESTED", createdAt: "2026-04-01T15:30:00" },
];

// ---- Consultation Notes ----
export const mockConsultationNotes: ConsultationNote[] = [
  { id: "cn-001", appointmentId: "apt-001", patientId: "pt-001", doctorId: "usr-002", doctorName: "Dr. Emily Chen", chiefComplaint: "Follow-up on RCT #36 — 2 week check", symptoms: "Mild tenderness on biting for first 3 days, now resolved. No spontaneous pain.", examination: "Tooth #36 non-tender to percussion. Temporary filling intact. Periapical X-ray shows resolving periapical radiolucency. No swelling or sinus tract.", diagnosis: "Root Canal Treated #36 — healing well", treatmentPlan: "Proceed with crown preparation at next visit (2 weeks). Take final impression. Temporary crown to be placed same day.", advice: "Avoid hard/sticky foods on #36. Maintain oral hygiene. Continue fluoride rinse nightly.", followUpDate: "2026-04-19", followUpNotes: "Schedule crown prep and impression. Discuss porcelain vs zirconia options.", createdAt: "2026-04-05T09:25:00" },
  { id: "cn-002", appointmentId: "apt-002", patientId: "pt-002", doctorId: "usr-003", doctorName: "Dr. Raj Patel", chiefComplaint: "Crown preparation for tooth #26 — session 1 of 2", symptoms: "Patient reports occasional sensitivity to cold on #26. No pain on biting.", examination: "Large MOD amalgam on #26 with recurrent caries at margins. Vitality test positive. No periapical involvement on X-ray.", diagnosis: "Defective restoration with secondary caries — indicated for full coverage crown", treatmentPlan: "Crown preparation today: remove old amalgam, place core build-up with composite, reduce tooth 1.5mm occlusal / 1mm axial. Take impression. Fit temporary crown. Cement final PFM crown at next visit.", advice: "Avoid chewing on temporary for 24 hrs. Floss gently around temp crown. If temp comes off, call clinic.", followUpDate: "2026-04-19", createdAt: "2026-04-05T09:40:00" },
];

// ---- Recent Activities (for dashboards) ----
export const mockActivities: ActivityItem[] = [
  { id: "act-001", user: "Dr. Emily Chen", action: "completed consultation", target: "Olivia Harper (PT-0001)", time: "2026-04-05T09:25:00", type: "consultation" },
  { id: "act-002", user: "Maria Santos", action: "checked in", target: "Emma Wilson (PT-0009)", time: "2026-04-05T09:52:00", type: "checkin" },
  { id: "act-003", user: "James Wilson", action: "created invoice", target: "INV-2026-0002 - Rs 481", time: "2026-04-05T09:30:00", type: "billing" },
  { id: "act-004", user: "Sophie Taylor", action: "logged call with", target: "Rebecca Stone (Lead)", time: "2026-04-05T09:15:00", type: "call" },
  { id: "act-005", user: "Dr. Raj Patel", action: "started procedure", target: "Ethan Brooks - Crown Prep #26", time: "2026-04-05T09:00:00", type: "procedure" },
  { id: "act-006", user: "Rachel Green", action: "recorded vitals for", target: "Ava Williams (PT-0005)", time: "2026-04-05T09:45:00", type: "vitals" },
  { id: "act-007", user: "Maria Santos", action: "registered new patient", target: "PT-0020 - Grace Robinson", time: "2026-04-05T08:30:00", type: "registration" },
  { id: "act-008", user: "System", action: "marked no-show", target: "James Anderson (APT-0016)", time: "2026-04-05T09:15:00", type: "system" },
];

// ---- Lab Tests ----
export const mockLabTests: LabTest[] = [
  { id: "lt-001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", testName: "Bitewing X-rays (4 films)", status: LabTestStatus.COMPLETED, results: { findings: "No interproximal caries detected. Bone levels within normal limits.", interpretation: "Normal" }, technician: "Dental Radiographer", completedAt: "2026-04-04T16:00:00", notes: "Routine bitewing series", createdAt: "2026-04-02" },
  { id: "lt-002", patientId: "pt-002", patientName: "Ethan Brooks", doctorId: "usr-003", doctorName: "Dr. Raj Patel", testName: "Zirconia Crown #26 (Dental Lab)", status: LabTestStatus.PROCESSING, technician: "External Dental Lab", collectedAt: "2026-04-04T10:00:00", createdAt: "2026-04-04" },
  { id: "lt-003", patientId: "pt-005", patientName: "Ava Williams", doctorId: "usr-003", doctorName: "Dr. Raj Patel", testName: "CBCT Scan - Implant Site #46", status: LabTestStatus.REQUESTED, notes: "Pre-implant evaluation: bone height and width", createdAt: "2026-04-05" },
  { id: "lt-004", patientId: "pt-009", patientName: "Emma Wilson", doctorId: "usr-003", doctorName: "Dr. Raj Patel", testName: "Periapical X-ray #37", status: LabTestStatus.SAMPLE_COLLECTED, technician: "Dental Radiographer", collectedAt: "2026-04-05T08:30:00", createdAt: "2026-04-04" },
  { id: "lt-005", patientId: "pt-015", patientName: "Lucas Jackson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", testName: "OPG (Panoramic X-ray)", status: LabTestStatus.COMPLETED, results: { findings: "Impacted #38 mesioangular; other wisdoms within normal eruption range", interpretation: "Refer for #38 extraction" }, technician: "Dental Radiographer", completedAt: "2026-04-03T14:00:00", createdAt: "2026-04-01" },
];

// ---- Triage Records ----
export const mockTriageRecords: Triage[] = [
  { id: "tri-001", patientId: "pt-005", patientName: "Ava Williams", appointmentId: "apt-003", temperature: 36.8, systolicBP: 120, diastolicBP: 80, heartRate: 72, respiratoryRate: 16, weight: 58, height: 165, oxygenSaturation: 98, bmi: "21.3", notes: "Patient appears healthy. No concerns.", urgencyLevel: "ROUTINE", recordedById: "usr-008", recordedByName: "Rachel Green", createdAt: "2026-04-05T09:45:00" },
  { id: "tri-002", patientId: "pt-009", patientName: "Emma Wilson", appointmentId: "apt-004", temperature: 36.6, systolicBP: 115, diastolicBP: 75, heartRate: 68, weight: 62, height: 170, oxygenSaturation: 99, bmi: "21.5", notes: "Gingival bleeding on probing; moderate plaque", skinObservations: "Generalized gingivitis, heavier on lower anteriors; calculus on lingual of 31-41", urgencyLevel: "ROUTINE", recordedById: "usr-008", recordedByName: "Rachel Green", createdAt: "2026-04-05T09:55:00" },
];

// ---- AI Transcriptions ----
export const mockAITranscriptions: AITranscription[] = [
  { id: "ai-001", appointmentId: "apt-001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", rawTranscript: "Dentist: How has tooth 36 been since the root canal?\nPatient: Much better. The pain is completely gone. There was a little tenderness when biting for the first few days but that's settled now.\nDentist: Good. Let me check. Opens wide... Any sensitivity to cold or hot?\nPatient: No, nothing.\nDentist: The temporary filling looks good. The X-ray shows the periapical area is healing. We can proceed with crown preparation in two weeks.\nPatient: Okay. What kind of crown will I need?\nDentist: For a lower molar, I'd recommend either a PFM or zirconia crown. Zirconia is stronger and looks better but costs more. We can discuss at the next visit.", structuredNote: { chiefComplaint: "Post-RCT follow-up #36", findings: "Asymptomatic, good healing on X-ray", plan: "Crown prep in 2 weeks; discuss PFM vs zirconia" }, summary: "RCT #36 healing well. Schedule crown preparation visit. Patient to decide crown material.", status: "COMPLETED", duration: 480, createdAt: "2026-04-05T09:25:00" },
];

// ---- Audit Log ----
export const mockAuditLogs: AuditLog[] = [
  { id: "al-001", userId: "usr-005", userName: "Maria Santos", action: "CREATE", module: "PATIENT", entityType: "Patient", entityId: "pt-020", details: "Registered new patient: Grace Robinson", ipAddress: "192.168.1.105", createdAt: "2026-04-05T08:30:00" },
  { id: "al-002", userId: "usr-002", userName: "Dr. Emily Chen", action: "CREATE", module: "CONSULTATION", entityType: "ConsultationNote", entityId: "cn-001", details: "Created consultation note for Olivia Harper", ipAddress: "192.168.1.110", createdAt: "2026-04-05T09:25:00" },
  { id: "al-003", userId: "usr-006", userName: "James Wilson", action: "CREATE", module: "BILLING", entityType: "Invoice", entityId: "inv-002", details: "Created invoice INV-2026-0002 - Rs 481", ipAddress: "192.168.1.108", createdAt: "2026-04-05T09:30:00" },
  { id: "al-004", userId: "usr-001", userName: "Dr. Sarah Mitchell", action: "LOGIN", module: "AUTH", entityType: "Session", entityId: "sess-001", details: "Admin login", ipAddress: "192.168.1.100", createdAt: "2026-04-05T08:30:00" },
  { id: "al-005", userId: "usr-007", userName: "Sophie Taylor", action: "CREATE", module: "CALL_CENTER", entityType: "Lead", entityId: "ld-001", details: "Created new lead: Rebecca Stone", ipAddress: "192.168.1.112", createdAt: "2026-04-05T09:15:00" },
];

// ---- Patient Documents ----
export const mockDocuments: PatientDocument[] = [
  { id: "doc-001", patientId: "pt-001", name: "Bitewing X-rays.pdf", type: DocumentType.LAB_RESULT, fileUrl: "/uploads/doc-001.pdf", fileSize: 245000, uploadedById: "usr-002", uploadedByName: "Dr. Emily Chen", notes: "4-film bitewing series — routine check", createdAt: "2026-04-04" },
  { id: "doc-002", patientId: "pt-001", name: "RCT Consent Form.pdf", type: DocumentType.CONSENT, fileUrl: "/uploads/doc-002.pdf", fileSize: 180000, uploadedById: "usr-005", uploadedByName: "Maria Santos", createdAt: "2026-03-14" },
  { id: "doc-003", patientId: "pt-002", name: "Before - Smile View.jpg", type: DocumentType.BEFORE_AFTER, fileUrl: "/uploads/doc-003.jpg", fileSize: 1200000, uploadedById: "usr-003", uploadedByName: "Dr. Raj Patel", notes: "Baseline photo before crown prep #26", createdAt: "2026-02-15" },
  { id: "doc-004", patientId: "pt-002", name: "After - Crown Cemented.jpg", type: DocumentType.BEFORE_AFTER, fileUrl: "/uploads/doc-004.jpg", fileSize: 1150000, uploadedById: "usr-003", uploadedByName: "Dr. Raj Patel", notes: "Post-cementation of PFM crown #26", createdAt: "2026-03-20" },
  { id: "doc-005", patientId: "pt-009", name: "Referral Letter.pdf", type: DocumentType.REPORT, fileUrl: "/uploads/doc-005.pdf", fileSize: 95000, uploadedById: "usr-005", uploadedByName: "Maria Santos", createdAt: "2026-04-04" },
];

// ---- Communication Logs ----
export const mockCommunicationLogs: CommunicationLog[] = [
  { id: "comm-001", patientId: "pt-001", type: "CALL", direction: "OUTBOUND", subject: "Appointment Reminder", content: "Called to remind about follow-up appointment on April 5", sentById: "usr-005", sentByName: "Maria Santos", createdAt: "2026-04-04T10:00:00" },
  { id: "comm-002", patientId: "pt-001", type: "SMS", direction: "OUTBOUND", subject: "Appointment Confirmation", content: "Your appointment with Dr. Emily Chen on April 5 at 9:00 AM is confirmed.", sentById: "usr-005", sentByName: "Maria Santos", createdAt: "2026-04-03T16:00:00" },
  { id: "comm-003", patientId: "pt-004", type: "EMAIL", direction: "OUTBOUND", subject: "Invoice Reminder", content: "Gentle reminder: Invoice INV-2026-0004 (Rs 856) is overdue. Please contact us for payment arrangements.", sentById: "usr-006", sentByName: "James Wilson", createdAt: "2026-04-01T09:00:00" },
  { id: "comm-004", patientId: "pt-010", type: "WHATSAPP", direction: "OUTBOUND", subject: "Package Update", content: "Hi Charlotte! You have 2 scaling sessions remaining in your Smile Essentials Plan. Would you like to book your next visit?", sentById: "usr-005", sentByName: "Maria Santos", createdAt: "2026-04-02T14:00:00" },
];

// ---- Skin History ----
export const mockSkinHistory: SkinHistory[] = [
  { id: "sh-001", patientId: "pt-001", condition: "Irreversible Pulpitis #36", affectedArea: "Lower left first molar (#36)", severity: "MODERATE", onsetDate: "2026-03-10", treatmentHistory: "Ibuprofen (symptomatic), RCT completed 2026-03-28", notes: "Deep caries on distal surface. Spontaneous pain relieved after RCT. Pending crown.", images: [] },
  { id: "sh-002", patientId: "pt-002", condition: "Defective MOD Restoration + Secondary Caries #26", affectedArea: "Upper left first molar (#26)", severity: "MODERATE", onsetDate: "2023-01-01", treatmentHistory: "Old amalgam placed ~10 years ago. Recurrent caries at margins. Crown prep in progress.", notes: "Indicated for full-coverage crown. Vitality positive — no RCT required.", images: [] },
  { id: "sh-003", patientId: "pt-005", condition: "Generalized Gingivitis", affectedArea: "Full mouth — heaviest lower anteriors", severity: "MILD", onsetDate: "2025-08-01", treatmentHistory: "New patient — no prior perio treatment", notes: "Moderate plaque and calculus. Scaling scheduled. Patient needs OHI.", images: [] },
];

// ---- Medical History ----
export const mockMedicalHistory: MedicalHistory[] = [
  { id: "mh-001", patientId: "pt-001", condition: "Type 2 Diabetes (controlled)", diagnosedDate: "2020-03-01", status: "CHRONIC", notes: "HbA1c 6.5. Relevant for perio status and implant planning. Delayed wound healing risk." },
  { id: "mh-002", patientId: "pt-004", condition: "Hypertension (mild)", diagnosedDate: "2022-06-01", status: "ACTIVE", notes: "Controlled with medication. Monitor BP before surgical procedures; avoid epinephrine overdose in LA." },
  { id: "mh-003", patientId: "pt-009", condition: "Penicillin Allergy", diagnosedDate: "2018-01-01", status: "CHRONIC", notes: "Use alternative antibiotics (e.g., azithromycin/clindamycin) for dental infections." },
];

// ---- Prescriptions ----
export const mockPrescriptions: Prescription[] = [
  { id: "rx-001", patientId: "pt-001", doctorId: "usr-002", doctorName: "Dr. Emily Chen", appointmentId: "apt-001", items: [
    { id: "rxi-001", medicineName: "Amoxicillin 500 mg", dosage: "1 capsule", frequency: "Three times daily", duration: "5 days", instructions: "Take after food. Complete the full course even if symptoms improve." },
    { id: "rxi-002", medicineName: "Ibuprofen 400 mg", dosage: "1 tablet", frequency: "Every 6 hrs as needed", duration: "3 days", instructions: "For post-procedure pain. Take with food. Max 4 tablets in 24 hrs." },
    { id: "rxi-003", medicineName: "Chlorhexidine Mouthwash 0.2%", dosage: "10 ml rinse", frequency: "Twice daily", duration: "2 weeks", instructions: "Swish for 30 seconds, then spit. Do not eat or drink for 30 min after use." },
  ], notes: "Post-RCT antibiotic + analgesic + antiseptic rinse. Review in 2 weeks.", createdAt: "2026-04-05" },
  { id: "rx-002", patientId: "pt-009", doctorId: "usr-003", doctorName: "Dr. Raj Patel", items: [
    { id: "rxi-004", medicineName: "Metronidazole 400 mg", dosage: "1 tablet", frequency: "Three times daily", duration: "5 days", instructions: "For acute periodontal infection. Avoid alcohol during treatment." },
    { id: "rxi-005", medicineName: "Fluoride Mouthwash 0.05%", dosage: "10 ml rinse", frequency: "Once daily at bedtime", duration: "Ongoing", instructions: "Use after brushing. Do not rinse with water afterwards." },
  ], createdAt: "2026-04-04" },
];

// ---- Patient Packages ----
export const mockPatientPackages: PatientPackage[] = [
  { id: "pp-001", patientId: "pt-010", packageId: "pkg-001", packageName: "Smile Essentials", purchaseDate: "2025-12-01", expiryDate: "2026-11-30", remainingSessions: { "Scaling & Polishing": 2, "Oral Examination": 1 }, status: "ACTIVE", invoiceId: "inv-pkg-001" },
  { id: "pp-002", patientId: "pt-001", packageId: "pkg-002", packageName: "Perio Care Plan", purchaseDate: "2026-01-15", expiryDate: "2027-01-15", remainingSessions: { "Scaling & Polishing": 3 }, status: "ACTIVE", invoiceId: "inv-pkg-002" },
  { id: "pp-003", patientId: "pt-004", packageId: "pkg-003", packageName: "Full Mouth Rehab", purchaseDate: "2025-11-01", expiryDate: "2026-10-31", remainingSessions: { "Porcelain Crown (PFM)": 2, "Root Canal Treatment — Molar": 1, "Dental Implant": 1 }, status: "ACTIVE", invoiceId: "inv-pkg-003" },
];

// ---- Room Allocations ----
export const mockRoomAllocations: RoomAllocation[] = [
  { id: "ra-001", patientId: "pt-001", patientName: "Olivia Harper", roomId: "rm-001", roomName: "Operatory 1 - Exam", doctorId: "usr-002", doctorName: "Dr. Emily Chen", admissionDate: "2026-04-05T09:00:00", status: "ACTIVE" },
  { id: "ra-002", patientId: "pt-002", patientName: "Ethan Brooks", roomId: "rm-002", roomName: "Operatory 2 - Surgery", doctorId: "usr-003", doctorName: "Dr. Raj Patel", admissionDate: "2026-04-05T09:00:00", status: "ACTIVE" },
  { id: "ra-003", patientId: "pt-014", patientName: "Amelia Moore", roomId: "rm-009", roomName: "Operatory 1 - Multi-Purpose", doctorId: "usr-009", doctorName: "Dr. Mark Williams", admissionDate: "2026-04-05T09:30:00", status: "ACTIVE" },
];
